### ISSUE TITLE
cargar conceptos scrum

### ISSUE THREAD

**Issue by mnvega28** [mnvega28/TSDWAD-S32-G1#1]
[README.md](https://github.com/mnvega28/TSDWAD-S32-G1/files/9040618/README.md)
Extraer del material de Scrum los siguientes conceptos: Ceremonias, Artefactos y Roles.
Registrar estos conceptos dentro del readme.md y renombrarlo como ConceptosScrum.md

**Comment by rominadvg** [comment]
[BASES DE DATOS RELACIONAL.pdf](https://github.com/mnvega28/TSDWAD-S32-G1/files/9041339/BASES.DE.DATOS.RELACIONAL.pdf)

**Comment by gartino** [comment]
ADJUNTO RESUMEN
[Introducción a GIT.pdf](https://github.com/mnvega28/TSDWAD-S32-G1/files/9050483/Introduccion.a.GIT.pdf)
